### PR TITLE
Simple build script

### PR DESCRIPTION
**Pull request by janhoy**
Script that checks for python, installs pelican and live-builds site

### CODE REVIEW

**Comment by adamwalz** [comment]
lgtm. The reason I suggested tasks.py instead of a shell script is that tasks.py is generated by `pelican-quickstart`. Since more ASF sites are moving to pelican it might have been easier for jenkins to standardize on one build command instead of now how buildbot uses `pelican content -t theme`

**Comment by adamwalz** [comment]
And it sounds like lucene-site is breaking ground in this effort so it may be viewed as a template for others

**Comment by janhoy** [comment]
i’m new to this. Just needed a small script that I could run when doing local dev so I don’t have to remember those two arguments or copy/paste :)

Feel free to whip up an alternative PR that does things the “pelican way”.

But for site publishing we don’t need pelican I think since infra is handling that with .asf.yaml, right?

**Comment by janhoy** [comment]
So any more feedback on this script? Should we try to do this "the pelican way" or just a simple script? Publishing of the site will happen through merging to staging/production branch so no need for fancy scripts there...

**Comment by uschindler** [comment]
I would make the listening server optional. By default it should only exec pelican. Additional command line parameters should be passed through.

Otherwise I have no strong feeling for this.

**Comment by janhoy** [comment]
Check out the last commits, you can now run the build script with -s to serve the site live, and it will pass on extra arguments to pelican

**Comment by uschindler** [comment]
All fine. Thanks. I cannot really test it as I am on travel to Fosdem, so go for it if it works for you.

**Pull request merged**
