### PR TITLE
Add Zach Chen to committer list

### PR DESCRIPTION
**Pull request by zacharymorn**

### CODE REVIEW

**Review by msokolov — APPROVED** [review]
hooray, you can push?

**Comment by zacharymorn** [comment]
Thanks Michael! I think I may still not have write access though.

Screen Shot 2021-04-20 at 8 19 38 PM

**Comment by HoustonPutman** [comment]
Have you linked your ASF and Github accounts here?

https://gitbox.apache.org/setup/

**Comment by zacharymorn** [comment]
> Have you linked your ASF and Github accounts here?
> 
> https://gitbox.apache.org/setup/

Ah thanks @HoustonPutman for the pointer! I must missed it earlier. I just linked them up and now able to see the merge PR button. Appreciate your help!

**Comment by mikemccand** [comment]
Woot!  First commit for @zacharymorn, congrats!

**Comment by zacharymorn** [comment]
The change looks good at staging https://lucene.staged.apache.org/whoweare.html . 

Hi @janhoy, I have a quick question. I see you had a few recent PRs to merge from `main` to `production` to deploy site changes. Are these changes typically batched up and deployed on a regular basis, or it's more on demand? I'm asking since I see there are a few commits in April before mine that are not deployed yet, so I wasn't sure if I sure go ahead and create a PR to merge all those commits into `production` including this one.

**Comment by janhoy** [comment]
It's up to you. Feel free to merge to prod immediately. If I fix a silly typo or something I sometimes just leave in in main branch for the next deploy...

**Comment by zacharymorn** [comment]
Thanks Jan! I'll open a PR for this then.

**Pull request merged**
