### PR TITLE
SOLR-13910 Add security pages news feeds for solr, core, and tlp

### PR DESCRIPTION
**Pull request by adamwalz**

### CODE REVIEW

**Comment by adamwalz** [comment]
Only 3237b49 is new. I'll update this PR when https://github.com/apache/lucene-site/pull/3 is merged

**Comment by janhoy** [comment]
I think we won't need security news for TLP or "core/java", since we have never felt the need to file a CVE until now. So let's just start with Solr and then add others if future need.

The Solr Security page should ideally contain some introduction about how to report a security issue (security@lucene.apache.org), link to the Confluence page discussing known false XSS issues that they don't need to report, and then below that the list of announcements. [Elastic's security page](https://www.elastic.co/community/security) could perhaps give some inspiration.

Is it possible to introduce custom properties in each post, so we could have e.g. `CVEnum: 2019-xyz` on top of every announcement and could then render the announcements as a table?

**Comment by adamwalz** [comment]
Makes sense. I'll add the intro.

Yes we can add custom properties. I'll try out a different layout more similar to the Elastic page.

**Comment by janhoy** [comment]
I could not see atom/rss enabled either. Should be very easy to do. I wonder if we should duplicate security announcements in the main solr news section or keep them separate? Or if we should just have one list of news, but with a `category` tag `news` or `security` and then select only security category for the /security.html page and the security RSS?

**Comment by uschindler** [comment]
+1

**Pull request merged**
