### PR TITLE
Remove Google Analytics from Lucene site

### PR DESCRIPTION
**Pull request by janhoy**
As done for Solr - get rid of GA script for Lucene site.

### CODE REVIEW

**Comment by janhoy** [comment]
@msokolov please review if you want Lucene to be GA free :-)

**Review by uschindler — APPROVED** [review]
All fine, it's basically the same like Solr.

**Comment by uschindler** [comment]
(sorry for late reply)

**Comment by msokolov** [comment]
Thanks, Jan and Uwe!

**Pull request merged**
