### PR TITLE
fix the example command

### PR DESCRIPTION
**Pull request by epugh**
Make the cut'n'paste work!

### CODE REVIEW

**Review by janhoy — APPROVED** [review]

**Comment by epugh** [comment]
@janhoy I noticed we use `pip3` in the readme, but `pip` in the script.   At least for me, `pip` doesn't work, so I upgraded.  However, not sure this is a good change for everyone!

**Comment by janhoy** [comment]
> @janhoy I noticed we use `pip3` in the readme, but `pip` in the script. At least for me, `pip` doesn't work, so I upgraded. However, not sure this is a good change for everyone!

+1
I think pip3 is safer and better.

**Comment by janhoy** [comment]
Actually when using venv, the `env/bin/activate` command will make `pip` an alias to `pip3` for you, so the end result is the same. But if you have chosen to work with your global python environment, and have git2 as default on your path, then it would be important to specify pip3. Since pip3 will always work, let's just use that.

If you want to merge this, remember to port the change to solr-site repo as well :)

**Comment by anshumg** [comment]
@epugh  - you might want to merge this in soon? :)

**Review by anshumg — APPROVED** [review]

**Pull request merged**
