### PR TITLE
Cve 2020 13941

### PR DESCRIPTION
**Pull request by dsmiley**

### CODE REVIEW

**Review by janhoy — COMMENTED** [review]
Can you follow the template of other reports, i.e. use the same headings, like `Versions Affected` and `Mitigation`?

**Comment by dsmiley** [comment]
Updated.  I didn't add "Vendor" which seems pointless.  Where did this template/convention come from?

**Review by janhoy — APPROVED** [review]
Looks good!

**Comment by janhoy** [comment]
The CVE template here I think is a copy of a kind of a layout some projects use for ANNOUNCE mails for CVEs, such as https://lists.apache.org/thread.html/rd48c72bd3255bda87564d4da3791517c074d94f8a701f93b85752651%40%3Cannounce.apache.org%3E, but I see that the style of those emails vary a lot. However, for the web site news it makes sense to keep the same structure since they are all listed in the same place.

The new CMS also has a possibility to define more "variables" on top of the template, so we could in theory define all CVE headings as structured metadata that could then be used in other templates such as the table on top of security page. But I think what we have now is a good balance?

**Pull request merged**
