### PR TITLE
Add solr pages to Pelican template

### PR DESCRIPTION
**Pull request by adamwalz**
This PR adds the ability to build the solr pages at lucene.apache.org/solr with Pelican. This change gets to rough parity with the current production site. Upcoming changes are required to inspect each page individually to ensure 100% parity as well as to DRY the templates to reduce needless code duplication introduced as part of the migration.

See README.md for instructions on building locally

### CODE REVIEW

**Comment by adamwalz** [comment]
Future PRs are expected to be smaller and easier to review, possibly with the exception of a refactoring PR to reduce code duplication.

**Comment by janhoy** [comment]
The solr section looks good. Of course there are lots of duplication in the templates but you already know that. Do you want me to squash your merges since 9a8bfaf into one?

**Comment by adamwalz** [comment]
Squashing is up to you depending on the norms of the project. I've been trying to keep the commits  logical so that each commit is buildable on its own and `git blame` can sort of describe the reasoning behind particular changes. If it were up to me I'd ask to rebase instead of squash.

**Comment by janhoy** [comment]
Good, they are all logically laid out, and I merged now, to quickly be able to iterate on the finishing touches. Appreciate the nice work you do here!

**Comment by janhoy** [comment]
Trying to link with LUCENE-9012

**Pull request merged**
