### PR TITLE
LUCENE-9057 Fix issues to get site up to par with current prod

### PR DESCRIPTION
**Pull request by janhoy**
https://issues.apache.org/jira/browse/LUCENE-9057

**This invalidates #9 which had a messy git history**

Here is an attempt to bring the new site up to date with current svn.

I have committed each svn commit separately onto this PR, and attributed with the original committers's id. I tried to fix the dates to the svn dates but could only do that for some commits.

Then there are some commits to fix various broken things such as bad links, outdated content, wiki links etc.

I am not quite sure why this PR appears to repeat some commits that are already in master branch (like "adding latest committers" by Houston and "manually trigger build" by Uwe). I think it may be because my local branch was not fully up to date with asf master before I started backporting from SVN, so I had to merge in those changes afterwards. This gives a bit messy history but I think the end result is ok.

There is still some work to do

The news pages show top N news, there should be some paging or "show all"
We still link to git-wip and call GitHub a "mirror"
Other

### CODE REVIEW

**Comment by uschindler** [comment]
Could you also update version numbers in the htaccess file? You can't backport this, but it's needed to have redirects working correctly.

I am also not sure about some absolute urls introduced. Can we not simply remove them? The page should never ever refer to lucene.apache.org directly.

Otherwise looks good.

**Comment by janhoy** [comment]
> Could you also update version numbers in the htaccess file? You can't backport this, but it's needed to have redirects working correctly.

Done

> I am also not sure about some absolute urls introduced. Can we not simply remove them? The page should never ever refer to lucene.apache.org directly.

Will have a look

**Comment by uschindler** [comment]
Thanks. We should possibly have an automatism.pelicsn should be able to also apply variable substitution in non markdown. I will try to figure that out.

Uwe

**Comment by janhoy** [comment]
I propose to merge this PR now and then to do followup fixes, ok?

**Comment by uschindler** [comment]
Yes. Merge it.

**Comment by janhoy** [comment]
Thanks for the review

**Pull request merged**
