### PR TITLE
Add Feng Guo to Commiter List

### PR DESCRIPTION
**Pull request by gf2121**

### CODE REVIEW

**Comment by uschindler** [comment]
Hi,
Better use a branch on your own repository.
Uwe

**Comment by gf2121** [comment]
Sorry, I'll delete the branch.

**Comment by uschindler** [comment]
You now need to merge "main" branch into branch "production" to make it visible on website. 👍 This is easiest locally, of course a PR may also work bit it's very noisy.

**Comment by gf2121** [comment]
Done. Thanks a lot for your guidance!

**Comment by gf2121** [comment]
Hi @uschindler ! Sorry to disturb. I have pushed the commit to the "production" branch" ([history](https://github.com/apache/lucene-site/commits/production)). It seems that https://lucene.staged.apache.org/whoweare.html has been updated, but https://lucene.apache.org/whoweare.html not. Is there a step I'm missing?

**Comment by uschindler** [comment]
It looks like the build it did not notice that you pushed to production branch. I can figure out how to manually do this.
I also did not get a mail to the commits@lucene.apache.org mailing list. Looks to me like an infrastructure problem that the notifications were not correctly sent.

**Comment by uschindler** [comment]
I opened: https://issues.apache.org/jira/browse/INFRA-22791

**Comment by gf2121** [comment]
Thank you!

**Comment by uschindler** [comment]
Hi, it looks like the push was not migrated to the Apache Gitbox. On Apache's server, the branches you deleted were already there. I cleaned all up manually.

You should better push NOT to Github, but to Apache's GIT server. The general workflow for pull requests is:
- Fork the github repository to your local account
- Also add another remote to your local checkout that points to Apache's Git server gitbox.apache.org
- Create branches and so on and open pull requests using your own fork.
- Once PRs are merged yo can switch your local repository to the Apache's main and merge from there and push directly to apache (website)

Some additional info for code changes in our main repo: For standard backports (e.g. main to branch_9x) the way to do this is: Checkout/switch to the target branch (e.g., branch_9x) on your local checkout and then cherry-pick the commin on main branch. Don't merge! After that push branch to ASF git server.

**Comment by uschindler** [comment]
So to fix the issue here: Could you push your "production" branch to https://gitbox.apache.org/repos/asf/lucene-site.git ?

**Comment by uschindler** [comment]
I pushed the changes from github manually to ASF Gitbox. Maybe the issue was that you used an invalid user account on Github (because the merge commit looks like coming from some different mail address).

**Comment by uschindler** [comment]
Site is now uptodate

**Comment by uschindler** [comment]
Looks like your mail address `*@bytedance.com` is not allowed to merge. Maybe you need to fix your repositories. Neverthless, it is recommended to work on ASF Gitbox for upstream changes and use Github only for forks.

**Comment by gf2121** [comment]
Thank you so much for such detailed and excellent commit guidance! I will follow them in the follow-up work.

> So to fix the issue here: Could you push your "production" branch to https://gitbox.apache.org/repos/asf/lucene-site.git ?

It was dinner time here so i did not see this in time. Sorry. And thanks again for helping push the changes!

**Pull request merged**
