### PR TITLE
Merge staged into production

### PR DESCRIPTION
**Pull request by janhoy**
Hide security warning box after 60 days.

### CODE REVIEW

**Comment by janhoy** [comment]
> Isn't this a duplicate?

Hehe, no, it is a PR to merge from master to production :)

**Comment by janhoy** [comment]
Added #17 as well, so we can merge both into production once validated in staging.

**Comment by janhoy** [comment]
Ok, both the security warning box and the new downloads links look god in staged, will put it in production now.

**Comment by uschindler** [comment]
I am still confused: how did you create the PR from master -> production?

**Comment by janhoy** [comment]
Just wanted to try another way to do the merge. But I think I like better the plain `git checkout production && git pull && git merge master && git push` :)

**Pull request merged**
