### PR TITLE
Add Greg Miller to committer list

### PR DESCRIPTION
**Pull request by gsmiller**

### CODE REVIEW

**Review by zacharymorn — APPROVED** [review]
LGTM!

**Comment by gsmiller** [comment]
Thanks @zacharymorn. It looks like my write permissions aren’t there yet so I’ll get that sorted out and merge this.

**Comment by zacharymorn** [comment]
Oh have you performed this setup? :D https://github.com/apache/lucene-site/pull/56#issuecomment-823772980

**Comment by gsmiller** [comment]
@zacharymorn ah, that's what I needed. Thanks!

**Pull request merged**
