### PR TITLE
LUCENE-9012 Setup minimal site with working Pelican build

### PR DESCRIPTION
**Pull request by adamwalz**
This PR contains a Pelican-ized version of lucene.apache.org for all sub-projects except for solr. The TLP page, Lucene Core, PyLucene, and Open Relevance all have a similar structure whereas the solr pages are pretty different. It would make sense for the solr pages to be reviewed in a different PR.

Since Pelican is new for this repo I have tried to keep commits logically separated to make it easier to follow the transition, as well as preserve the ability to `git blame` line by line to see when content was originally added. For this reason it would be best to rebase this PR rather than squash and merge. Rebasing will keep a history of renamed files from `git mv` whereas squashing will lose that history.

### CODE REVIEW

**Comment by adamwalz** [comment]
One reason for the massive number of changed files (711) is that I broke up the news files into one file per news item. This allows for limiting the number of news items in the TLP page to the most recent N without having to delete old events from the markdown.

```
{% for article in articles[:15] %}
{{ article.content }}
{{ endfor }}
```

**Comment by janhoy** [comment]
@adamwalz Can you add a README.md with basic instructions to build the site locally (including what tools to install)? Then I'll try it here and merge once it's working. No need to describe the .asf.yml stuff in README yet

**Comment by adamwalz** [comment]
@janhoy Yes I've added a README as well as a `requirements.txt` file containing the list of python dependencies.

**Comment by janhoy** [comment]
Minor: Perhaps below the news on main page show a text "For older news articles, see <link>" and link to the news page?

**Comment by adamwalz** [comment]
Agreed on all points. I'd like to rebase this and iterate on issues in followup PRs. I'm expecting to find more Pelican idiosyncrasies and differences from the current production site as we go along.

The next two PRs which could also be large would be
1. The solr pages
2. DRYing this out a little. There's a lot of duplicate code

After that changes such as dead links, build documentation, and unnecessary settings can be made in much smaller more reviewable PRs.

**Pull request merged**
